Repository thinktecture/relayserver, pull requests merged in 2018-02, with the labels that each got.

#88 Make the OnPremiseConnector library a netstandard1.3 library
  Shared/AssemblyInfo.shared.cs
  Thinktecture.Relay.CustomCodeDemo/Thinktecture.Relay.CustomCodeDemo.csproj
  Thinktecture.Relay.OnPremiseConnector/IdentityModel/BasicAuthenticationHeaderValue.cs
  Thinktecture.Relay.OnPremiseConnector/IdentityModel/HttpClientExtensions.cs
  Thinktecture.Relay.OnPremiseConnector/IdentityModel/OAuth2Client.cs
  Thinktecture.Relay.OnPremiseConnector/IdentityModel/OAuth2Constants.cs
  Thinktecture.Relay.OnPremiseConnector/IdentityModel/TokenResponse.cs
  Thinktecture.Relay.OnPremiseConnector/Properties/AssemblyInfo.cs
  Thinktecture.Relay.OnPremiseConnector/RelayServerConnector.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IRelayServerConnectionFactory.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnectionFactory.cs
  Thinktecture.Relay.OnPremiseConnector/Thinktecture.Relay.OnPremiseConnector.csproj
  Thinktecture.Relay.OnPremiseConnector/app.config
  Thinktecture.Relay.OnPremiseConnector/packages.config
  Thinktecture.Relay.OnPremiseConnectorService/App.config
  Thinktecture.Relay.OnPremiseConnectorService/OnPremisesService.cs
  Thinktecture.Relay.OnPremiseConnectorService/Thinktecture.Relay.OnPremiseConnectorService.csproj
  Thinktecture.Relay.OnPremiseConnectorService/packages.config
  Thinktecture.Relay.Server.Test/NoAsyncVoidTest.cs
  Thinktecture.Relay.Server.Test/Thinktecture.Relay.Server.Test.csproj
  Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
  Thinktecture.Relay.sln
Labels: enhancement

#93 General release preparation
  Documentation/de/3-installation.md
  Documentation/de/5-relayserver-interceptor-entwicklung.md
  Documentation/de/relayserver.md
  Documentation/en/1-what-is-thinktecture-relayserver.md
  Documentation/en/3-installation.md
  Documentation/en/5-relayserver-interceptor-development.md
  Documentation/en/relayserver.md
  Shared/AssemblyInfo.shared.cs
  Thinktecture.Relay.CustomCodeDemo/CustomCodeModule.cs
  Thinktecture.Relay.ManagementWeb/assets/app.css
  Thinktecture.Relay.ManagementWeb/assets/app.responsive.css
  Thinktecture.Relay.ManagementWeb/index.html
  Thinktecture.Relay.ManagementWeb/libs/font-awesome/css/font-awesome.min.css
  Thinktecture.Relay.OnPremiseConnector/IRelayServerConnector.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/AcknowledgmentMode.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/IOnPremiseTargetRequest.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/IOnPremiseTargetResponse.cs
  Thinktecture.Relay.OnPremiseConnector/RelayServerConnector.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
  Thinktecture.Relay.Server.Test/Helper/ConfigurationDummy.cs
  Thinktecture.Relay.Server/App.config
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqMessageDispatcher.cs
  Thinktecture.Relay.Server/Config/Configuration.cs
  Thinktecture.Relay.Server/Config/IConfiguration.cs
  Thinktecture.Relay.Server/OnPremise/IOnPremiseConnectorRequest.cs
  Thinktecture.Relay.Server/OnPremise/IOnPremiseConnectorResponse.cs
  Thinktecture.Relay.Server/Program.cs
  Thinktecture.Relay.Server/Properties/AssemblyInfo.cs
  Thinktecture.Relay.Server/RelayService.cs
  Thinktecture.Relay.sln.DotSettings
  Thinktecture.Relay/Server/AcknowledgmentMode.cs
  Thinktecture.Relay/Server/Interceptor/IInterceptedResponse.cs
  Thinktecture.Relay/Server/Interceptor/IReadOnlyInterceptedRequest.cs
  delete-bin-and-obj-folders.ps1
Labels: cosmetic

#86 Set ContentLength for all requests, as we need the value on the request for logging
  Thinktecture.Relay.Server/Diagnostics/RequestLogger.cs
  Thinktecture.Relay.Server/Http/OnPremiseRequestBuilder.cs
Labels: bug

#87 Fix nullref in NoCacheAttribute
  Thinktecture.Relay.Server/Http/Filters/NoCacheAttribute.cs
Labels: bug

#64 Made access token lifetime configurable
  Documentation/de/3-installation.md
  Documentation/en/3-installation.md
  Thinktecture.Relay.OnPremiseConnector/RelayServerConnector.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/HeartbeatChecker.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IHeartbeatChecker.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IMaintenanceLoop.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IRelayServerConnection.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IRelayServerConnectionFactory.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/ITokenExpiryChecker.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/MaintenanceLoop.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnectionFactory.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/TokenExpiryChecker.cs
  Thinktecture.Relay.OnPremiseConnector/Thinktecture.Relay.OnPremiseConnector.csproj
  Thinktecture.Relay.OnPremiseConnectorService/App.config
  Thinktecture.Relay.OnPremiseConnectorService/Configuration/SecurityElement.cs
  Thinktecture.Relay.OnPremiseConnectorService/OnPremisesService.cs
  Thinktecture.Relay.Server.Test/Helper/ConfigurationDummy.cs
  Thinktecture.Relay.Server/App.config
  Thinktecture.Relay.Server/Config/Configuration.cs
  Thinktecture.Relay.Server/Config/IConfiguration.cs
  Thinktecture.Relay.Server/Security/AuthorizationServerProvider.cs
  Thinktecture.Relay.Server/Startup.cs
Labels: enhancement

#89 Combine all management web styles and additionally uglify scripts
  .gitignore
  GulpTasks/managementWeb.js
  Thinktecture.Relay.ManagementWeb/app/linkDetails/tabs/charts.js
  Thinktecture.Relay.ManagementWeb/index.html
  Thinktecture.Relay.Server/App.config
  gulp.config.js
  gulpfile.js
  package-lock.json
  package.json
Labels: enhancement

#94 Fixed wrong parsing of connector timeout value as int instead of timespan
  Thinktecture.Relay.Server/Config/Configuration.cs
Labels: bug

#97 Changed TokenRefreshWindow and RequestTimeout to TimeSpans
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/IOnPremiseTargetConnectorFactory.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/OnPremiseInProcTargetConnector.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/OnPremiseInProcTargetConnectorBase.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/OnPremiseTargetConnectorFactory.cs
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/OnPremiseWebTargetConnector.cs
  Thinktecture.Relay.OnPremiseConnector/RelayServerConnector.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/IRelayServerConnectionFactory.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnectionFactory.cs
Labels: cosmetic, enhancement

#95 Temporary storage period is now at least 2x connector callback timeout
  Documentation/de/3-installation.md
  Documentation/en/3-installation.md
  Thinktecture.Relay.Server/Config/Configuration.cs
Labels: bug

#96 Temporary file store handling improved, fixed and simplified
  Documentation/de/relayserver.md
  Documentation/en/5-relayserver-interceptor-development.md
  Documentation/en/relayserver.md
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/IOnPremiseTargetRequest.cs
  Thinktecture.Relay.Server/Communication/OnPremiseConnectorCallbackFactory.cs
  Thinktecture.Relay.Server/Controller/ClientController.cs
  Thinktecture.Relay.Server/Controller/ResponseController.cs
  Thinktecture.Relay.Server/Http/HttpResponseMessageBuilder.cs
  Thinktecture.Relay.Server/Interceptor/InterceptedResponse.cs
  Thinktecture.Relay.Server/OnPremise/IOnPremiseConnectorRequest.cs
  Thinktecture.Relay.Server/OnPremise/IOnPremiseConnectorResponse.cs
  Thinktecture.Relay.Server/SignalR/FilePostDataTemporaryStore.cs
  Thinktecture.Relay.Server/SignalR/IPostDataTemporaryStore.cs
  Thinktecture.Relay.Server/SignalR/InMemoryPostDataTemporaryStore.cs
  Thinktecture.Relay/Server/Interceptor/IInterceptedRequest.cs
Labels: bug, enhancement

#101 Increase StreamContent buffer size
  Thinktecture.Relay.OnPremiseConnector/OnPremiseTarget/OnPremiseWebTargetRequestMessageBuilder.cs
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
  Thinktecture.Relay.Server/Controller/RequestController.cs
  Thinktecture.Relay.Server/Http/HttpResponseMessageBuilder.cs
Labels: bug

#99 Check for error and raise the reason as an error
  Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
Labels: enhancement
