Repository thinktecture/relayserver, pull requests merged in 2020-05, with the labels that each got.

#212 Acknowledge on correct request channel
  Thinktecture.Relay.Server.Test/Communication/BackendCommunicationTests/Prepare.cs
  Thinktecture.Relay.Server/Communication/BackendCommunication.cs
  Thinktecture.Relay.Server/Communication/IBackendCommunication.cs
  Thinktecture.Relay.Server/Communication/IMessageDispatcher.cs
  Thinktecture.Relay.Server/Communication/InProcess/InProcessMessageDispatcher.cs
  Thinktecture.Relay.Server/Communication/InProcess/RequestSubjectContext.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/AcknowledgeRequest.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/IAcknowledgeRequest.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/IRabbitMqAcknowledgeableChannel.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/IRabbitMqRequestChannel.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqAcknowledgeChannel.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqChannelBase.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqMessageDispatcher.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqRequestChannel.cs
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqResponseChannel.cs
  Thinktecture.Relay.Server/Controller/RequestController.cs
  Thinktecture.Relay.Server/DependencyInjection/RelayServerModule.cs
  Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
Labels: bug, legacy

#211 Add postman collection with example requests
  src/samples/RelayServerCore.postman_collection.json
Labels: documentation

#214 Prevent deactivating an already deactivated connection
  Thinktecture.Relay.Server/Communication/OnPremiseConnectionHeartbeater.cs
Labels: bug, legacy

#192 Fix NRE when accessing empty bodies in intercepted requests and responses
  Documentation/de/relayserver.md
  Documentation/en/relayserver.md
  Thinktecture.Relay.Server/Interceptor/IInterceptedStream.cs
  Thinktecture.Relay.Server/Interceptor/InterceptedRequest.cs
  Thinktecture.Relay.Server/Interceptor/InterceptedResponse.cs
  Thinktecture.Relay.Server/Interceptor/InterceptedStreamExtensions.cs
  Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
Labels: bug, legacy

#216 Send config only to supporting OPCs
  Thinktecture.Relay.Server/Communication/BackendCommunication.cs
Labels: bug, legacy

#218 Allow own on-premise context implementation via DI
  Thinktecture.Relay.CustomCodeDemo/CustomCodeModule.cs
  Thinktecture.Relay.CustomCodeDemo/DemoOnPremiseConnectorContext.cs
  Thinktecture.Relay.CustomCodeDemo/Thinktecture.Relay.CustomCodeDemo.csproj
  Thinktecture.Relay.Server/Communication/IOnPremiseConnectionContext.cs
  Thinktecture.Relay.Server/DependencyInjection/RelayServerModule.cs
  Thinktecture.Relay.Server/SignalR/OnPremisesConnection.cs
  Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
  Thinktecture.Relay/Server/Communication/IOnPremiseConnectionContext.cs
  Thinktecture.Relay/Server/Communication/OnPremiseConnectionContext.cs
Labels: legacy, new feature

#219 Add additional properties in JSON to request root
  Thinktecture.Relay.CustomCodeDemo/DemoRequestInterceptor.cs
  Thinktecture.Relay.Server/Interceptor/InterceptedRequest.cs
  Thinktecture.Relay.Server/OnPremise/OnPremiseConnectorRequest.cs
  Thinktecture.Relay.Server/SignalR/OnPremisesConnection.cs
  Thinktecture.Relay/Server/Interceptor/IInterceptedRequest.cs
  Thinktecture.Relay/Server/OnPremise/IOnPremiseConnectorRequest.cs
Labels: legacy, new feature

#220 Update release notes
  Documentation/de/relayserver.md
  Documentation/en/relayserver.md
Labels: documentation, legacy

#221 Instantly remove PING request from queue
  Documentation/de/relayserver.md
  Documentation/en/relayserver.md
  Shared/ProjectProperties.shared.props
  Thinktecture.Relay.Server/Controller/ManagementWeb/LinkController.cs
Labels: enhancement, legacy

#223 Make the Entity Framework context public
  Documentation/de/relayserver.md
  Documentation/en/relayserver.md
  Thinktecture.Relay.Server/Repository/DbModels/DbActiveConnection.cs
  Thinktecture.Relay.Server/Repository/DbModels/DbLink.cs
  Thinktecture.Relay.Server/Repository/DbModels/DbRequestLogEntry.cs
  Thinktecture.Relay.Server/Repository/DbModels/DbTraceConfiguration.cs
  Thinktecture.Relay.Server/Repository/RelayContext.cs
Labels: enhancement, legacy
