Repository thinktecture/relayserver, pull requests merged in 2020-11, with the labels that each got.

#280 Optimize multi-stage docker build
  src/.dockerignore
  src/.idea/.idea.Thinktecture.Relay/.idea/runConfigurations/Relay_Server.xml
  src/Thinktecture.Relay.sln
  src/build-docker-images.ps1
  src/docker/Thinktecture.Relay.Connector.Docker/Dockerfile
  src/docker/Thinktecture.Relay.IdentityServer.Docker/Dockerfile
  src/docker/Thinktecture.Relay.ManagementApi.Docker/Dockerfile
  src/docker/Thinktecture.Relay.Server.Docker/Dockerfile
  src/docker/Thinktecture.Relay.StatisticsApi.Docker/Dockerfile
  src/docker/build-images.ps1
  src/docker/run-dependencies.ps1
  src/docker/seed-data.ps1
Labels: docker, enhancement, infrastructure

#281 Add the http context to the relay context
  src/Thinktecture.Relay.Server.Abstractions/Transport/IRelayContext.cs
  src/Thinktecture.Relay.Server/Middleware/RelayContext.cs
  src/Thinktecture.Relay.Server/ServiceCollectionExtensions.cs
Labels: enhancement

#287 Make seed script work in full environment and update docs
  docs/deployment.md
  src/docker/seed-data.ps1
Labels: documentation, infrastructure

#288 Move projects into solution folders
  src/Thinktecture.Relay.sln
Labels: cosmetic

#285 Add support for interceptors
  src/Thinktecture.Relay.Connector/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/ServiceCollectionExtensions.cs
  src/Thinktecture.Relay.Server.Abstractions/DependencyInjection/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server/DependencyInjection/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
  src/docker/Thinktecture.Relay.Server.Docker/ClientRequestInterceptor.cs
  src/docker/Thinktecture.Relay.Server.Docker/Startup.cs
Labels: enhancement

#293 Add X-Forwarded-Header interceptor
  CONTRIBUTING.md
  src/Thinktecture.Relay.Interceptors.XForwardedHeader/ClientRequestInterceptor.cs
  src/Thinktecture.Relay.Interceptors.XForwardedHeader/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Interceptors.XForwardedHeader/Thinktecture.Relay.Interceptors.XForwardedHeader.csproj
  src/Thinktecture.Relay.sln
Labels: enhancement

#295 Move interceptors into one assembly
  src/Thinktecture.Relay.Interceptors/ForwardedHeaderInterceptor.cs
  src/Thinktecture.Relay.Interceptors/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Interceptors/Thinktecture.Relay.Interceptors.csproj
  src/Thinktecture.Relay.sln
Labels: cosmetic

#298 Allow web target configuration from appsettings
  src/Thinktecture.Relay.Connector.Abstractions/Options/RelayConnectorOptions.cs
  src/Thinktecture.Relay.Connector.Abstractions/Options/RelayWebTargetOptions.cs
  src/Thinktecture.Relay.Connector.Abstractions/RelayTargets/RelayTargetRegistration.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ConnectionFactory.cs
  src/Thinktecture.Relay.Connector/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/RelayTargets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayTargetService.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Startup.cs
  src/docker/Thinktecture.Relay.Connector.Docker/appsettings.Development.json
Labels: enhancement

#302 Make register and unregister for targets synchronous
  src/Thinktecture.Relay.Connector.Abstractions/RelayTargetRegistry.cs
  src/Thinktecture.Relay.Connector/Options/RelayConnectorPostConfigureOptions.cs
Labels: cosmetic

#303 Expose connection relevant events on connector connection
  src/Thinktecture.Relay.Connector.Abstractions/IConnectorConnection.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/SignalRConnectorConnection.cs
Labels: enhancement
