Repository thinktecture/relayserver, pull requests merged in 2020-09, with the labels that each got.

#252 Remove stored body content when needed
  src/Thinktecture.Relay.Abstractions/Acknowledgement/AcknowledgeRequest.cs
  src/Thinktecture.Relay.Abstractions/Acknowledgement/IAcknowledgeRequest.cs
  src/Thinktecture.Relay.Abstractions/ClientRequestExtensions.cs
  src/Thinktecture.Relay.Abstractions/TargetResponseExtensions.cs
  src/Thinktecture.Relay.Abstractions/Transport/IConnectorTransport.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ServerConnection.cs
  src/Thinktecture.Relay.Connector/RelayTargets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Server.Abstractions/IBodyStore.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/AcknowledgeCoordinator.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/TenantHandler.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/ConnectorHub.cs
  src/Thinktecture.Relay.Server/Controllers/BodyContentController.cs
  src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
  src/Thinktecture.Relay.Server/Transport/FileBodyStore.cs
  src/Thinktecture.Relay.Server/Transport/InMemoryBodyStore.cs
  src/Thinktecture.Relay.Server/Transport/ResponseCoordinator.cs
Labels: infrastructure

#253 Add acknowledge controller for manual acknowledgement
  src/Thinktecture.Relay.Abstractions/Acknowledgement/IAcknowledgeRequest.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/IAcknowledgeCoordinator.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ServerDispatcher.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/TenantHandler.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/ConnectorHub.cs
  src/Thinktecture.Relay.Server/Controllers/AcknowledgeController.cs
  src/Thinktecture.Relay.Server/Factories/RelayClientRequestFactory.cs
  src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
  src/Thinktecture.Relay.Server/ServiceCollectionExtensions.cs
  src/Thinktecture.Relay.Server/Transport/AcknowledgeCoordinator.cs
Labels: enhancement

#254 Coordinate response to allow shortcut on same server
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ConnectionFactory.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ServerConnection.cs
  src/Thinktecture.Relay.Connector/Authentication/AccessTokenProvider.cs
  src/Thinktecture.Relay.Connector/Options/ConfigureAccessTokenManagementOptions.cs
  src/Thinktecture.Relay.Connector/RelayTargets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayWebTarget.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/IResponseCoordinator.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/TenantConnectorAdapterRegistry.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ServerDispatcher.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ServerHandler.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/TenantDispatcher.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/TenantHandler.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/ConnectorHub.cs
  src/Thinktecture.Relay.Server/Factories/RelayClientRequestFactory.cs
  src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
  src/Thinktecture.Relay.Server/ServiceCollectionExtensions.cs
  src/Thinktecture.Relay.Server/Transport/AcknowledgeCoordinator.cs
  src/Thinktecture.Relay.Server/Transport/FileBodyStore.cs
  src/Thinktecture.Relay.Server/Transport/ResponseCoordinator.cs
Labels: enhancement

#258 Configure shortcut via options
  src/Thinktecture.Relay.IdentityServer/Stores/RelayServerTenantStore.cs
  src/Thinktecture.Relay.Server.Abstractions/DisposeAction.cs
  src/Thinktecture.Relay.Server.Abstractions/RelayServerOptions.cs
  src/Thinktecture.Relay.Server/DependencyInjection/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server/ServiceCollectionExtensions.cs
  src/Thinktecture.Relay.Server/Transport/RequestCoordinator.cs
  src/Thinktecture.Relay.Server/Transport/ResponseCoordinator.cs
Labels: enhancement

#259 Move target registration to options to allow dynamic change during runtime
  src/Thinktecture.Relay.Connector.Abstractions/Constants.cs
  src/Thinktecture.Relay.Connector.Abstractions/IRelayTargetOptions.cs
  src/Thinktecture.Relay.Connector.Abstractions/RelayConnectorOptions.cs
  src/Thinktecture.Relay.Connector.Abstractions/RelayTargets/RelayTargetRegistration.cs
  src/Thinktecture.Relay.Connector.Abstractions/RelayTargets/RelayTargetServiceOptions.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ConnectionFactory.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ConnectorConnection.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/RelayConnector.cs
  src/Thinktecture.Relay.Connector/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/RelayTargets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayTargetRegistration.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayTargetResponseFactory.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayTargetService.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayWebTarget.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayWebTargetOptions.cs
  src/Thinktecture.Relay.Connector/ServiceCollectionExtensions.cs
  src/Thinktecture.Relay.Server.Abstractions/RelayServerOptions.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/TenantConnectorAdapterRegistry.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/ConnectorHub.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/RelayServerBuilderExtensions.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Startup.cs
Labels: enhancement

#261 First stabilizing efforts
  src/Thinktecture.Relay.Abstractions/Acknowledgement/AcknowledgeMode.cs
  src/Thinktecture.Relay.Abstractions/ClientRequestExtensions.cs
  src/Thinktecture.Relay.Abstractions/Extensions/ClientRequestExtensions.cs
  src/Thinktecture.Relay.Abstractions/Extensions/EventExtensions.cs
  src/Thinktecture.Relay.Abstractions/Extensions/StreamExtensions.cs
  src/Thinktecture.Relay.Abstractions/Extensions/TargetResponseExtensions.cs
  src/Thinktecture.Relay.Abstractions/Transport/ITargetResponse.cs
  src/Thinktecture.Relay.Abstractions/Transport/TargetResponse.cs
  src/Thinktecture.Relay.Connector.Abstractions/IRelayTargetResponseFactory.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/ConnectorConnection.cs
  src/Thinktecture.Relay.Connector.Protocols.SignalR/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/RelayConnectorBuilderExtensions.cs
  src/Thinktecture.Relay.Connector/RelayTargets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayTargetResponseFactory.cs
  src/Thinktecture.Relay.Connector/RelayTargets/RelayWebTarget.cs
  src/Thinktecture.Relay.Server.Abstractions/Extensions/ClaimsPrincipalExtensions.cs
  src/Thinktecture.Relay.Server.Abstractions/IServerHandler.cs
  src/Thinktecture.Relay.Server.Abstractions/Persistence/ITenantRepository.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/IRelayClientRequestFactory.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/IRelayContext.cs
  src/Thinktecture.Relay.Server.Abstractions/Transport/TenantConnectorAdapterRegistry.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ModelExtensions.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ServerDispatcher.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/ServerHandler.cs
  src/Thinktecture.Relay.Server.Protocols.RabbitMq/TenantHandler.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/ConfigureJwtBearerOptions.cs
  src/Thinktecture.Relay.Server.Protocols.SignalR/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server/DependencyInjection/RelayServerBuilderExtensions.cs
  src/Thinktecture.Relay.Server/Factories/RelayClientRequestFactory.cs
  src/Thinktecture.Relay.Server/Middleware/RelayContext.cs
  src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
  src/Thinktecture.Relay.Server/Services/RelayTargetResponseWriter.cs
  src/Thinktecture.Relay.Server/Transport/ResponseCoordinator.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Program.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Startup.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Thinktecture.Relay.Connector.Docker.csproj
  src/docker/Thinktecture.Relay.Docker/DockerUtils.cs
  src/docker/Thinktecture.Relay.Docker/StreamDestructuringPolicy.cs
Labels: enhancement

#267 Allow usage of connector as windows and linux services
  src/docker/Thinktecture.Relay.Connector.Docker/Program.cs
  src/docker/Thinktecture.Relay.Connector.Docker/Thinktecture.Relay.Connector.Docker.csproj
  src/docker/Thinktecture.Relay.Connector.Docker/install-service.ps1
  src/docker/Thinktecture.Relay.Connector.Docker/remove-service.ps1
Labels: infrastructure

#272 Fix logging of uris
  Documentation/de/relayserver.md
  Documentation/en/relayserver.md
  Shared/AssemblyInfo.shared.cs
  Shared/ProjectProperties.shared.props
  Thinktecture.Relay.OnPremiseConnector.InterceptorSample/Thinktecture.Relay.OnPremiseConnector.InterceptorSample.csproj
  Thinktecture.Relay.Server/Communication/RabbitMq/RabbitMqChannelBase.cs
  Thinktecture.Relay.Server/Extensions/StringExtensions.cs
  Thinktecture.Relay.Server/SignalR/OnPremisesConnection.cs
  Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
Labels: bug
