Repository thinktecture/relayserver, pull requests merged in 2023-08, with the labels that each got.

#420 Update dependencies to latest .NET 6
  src/Thinktecture.Relay.Abstractions/Thinktecture.Relay.Abstractions.csproj
  src/Thinktecture.Relay.Connector.Protocols.SignalR/Thinktecture.Relay.Connector.Protocols.SignalR.csproj
  src/Thinktecture.Relay.Server.Abstractions/Thinktecture.Relay.Server.Abstractions.csproj
  src/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.PostgreSql/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.PostgreSql.csproj
  src/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.SqlServer/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.SqlServer.csproj
  src/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.csproj
  src/Thinktecture.Relay.Server.Protocols.SignalR/Thinktecture.Relay.Server.Protocols.SignalR.csproj
  src/Thinktecture.Relay.Server/Thinktecture.Relay.Server.csproj
  src/docker/Thinktecture.Relay.Connector.Docker/Thinktecture.Relay.Connector.Docker.csproj
  src/docker/Thinktecture.Relay.Docker/Thinktecture.Relay.Docker.csproj
  src/docker/Thinktecture.Relay.ManagementApi.Docker/Thinktecture.Relay.ManagementApi.Docker.csproj
  src/tools/MigrationCreation.PostgreSql/MigrationCreation.PostgreSql.csproj
  src/tools/MigrationCreation.SqlServer/MigrationCreation.SqlServer.csproj
Labels: dependencies

#424 Fix failing SQL Server migrations
  src/Thinktecture.Relay.Server.Persistence.EntityFrameworkCore.SqlServer/Migrations/ConfigurationDb/20201124123541_Rename_Properties.cs
Labels: bug

#425 http headers are to be treated case-insensitive
  src/Thinktecture.Relay.Abstractions/Extensions/ClientRequestExtensions.cs
  src/Thinktecture.Relay.Connector/Targets/ClientRequestHandler.cs
  src/Thinktecture.Relay.Connector/Targets/RelayWebTarget.cs
  src/Thinktecture.Relay.Server/Transport/RelayClientRequestFactory.cs
Labels: bug

#427 Remove health check mapping
  src/docker/Thinktecture.Relay.Server.Docker/Startup.cs
Labels: bug

#429 Set default request expiration greater than default target timeout
  docs/configuration.md
  src/Thinktecture.Relay.Server.Abstractions/RelayServerOptions.cs
Labels: enhancement, documentation

#435 Recover faster when IdSrv isn't reachable
  src/docker/Thinktecture.Relay.Server.Docker/Startup.cs
Labels: bug, docker

#438 Disable keep-alive when retrying requests
  src/Thinktecture.Relay.Connector.Abstractions/Constants.cs
  src/Thinktecture.Relay.Connector.Abstractions/RelayConnectorOptions.cs
  src/Thinktecture.Relay.Connector/Options/AccessTokenManagementConfigureOptions.cs
  src/Thinktecture.Relay.Connector/Options/RelayConnectorPostConfigureOptions.cs
  src/Thinktecture.Relay.Connector/ServiceCollectionExtensions.cs
Labels: bug
